[package]
name = "mqtt-healthchecker-rs"
version = "0.1.0"
authors = ["Yusuke Sato <yusuke1.sato9.git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
